-- Tabela: d_user_stores
CREATE TABLE analytics.d_user_stores (
    ID             NUMBER(11) NOT NULL,
    LOJA           VARCHAR2(255 BYTE),
    ID_USERS       NUMBER(11),
    CONSTRAINT lojas_users_pk PRIMARY KEY (ID)
);

-- Tabela: d_users
CREATE TABLE analytics.d_users (
    ID       NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    NAME     VARCHAR2(255 BYTE),
    PASSWORD VARCHAR2(255 BYTE),
    ROLE     VARCHAR2(25 BYTE) DEFAULT 'USER',
    CONSTRAINT users_pk PRIMARY KEY (ID)
);

-- Tabela: f_caixa
CREATE TABLE analytics.f_caixa (
    ID               NUMBER(15) NOT NULL,
    DATA             DATE NOT NULL,
    NUM_DOC          VARCHAR2(15 BYTE) NOT NULL,
    ORIGEM           VARCHAR2(250 BYTE),
    TIPO_OPERACAO    VARCHAR2(20 BYTE) NOT NULL,
    VALOR            NUMBER(10, 2) NOT NULL,
    STATUS           NUMBER NOT NULL,
    ID_USERS         NUMBER NOT NULL,
    ID_STORES        NUMBER(11) NOT NULL,
    CONSTRAINT f_caixa_pk PRIMARY KEY (ID),
    CONSTRAINT f_caixa_id_users_fk FOREIGN KEY (ID_USERS) REFERENCES analytics.d_users (ID),
    CONSTRAINT f_caixa_id_stores_fk FOREIGN KEY (ID_STORES) REFERENCES analytics.d_user_stores (ID)
);

-- Relacionamento entre d_user_stores e d_users
ALTER TABLE analytics.d_user_stores
    ADD CONSTRAINT fk_lojas_users_users
        FOREIGN KEY (ID_USERS) REFERENCES analytics.d_users (ID);
